#!/bin/bash

setup() {
  bun i
  vendor
}

vendor() {
  mkdir -p vendor

  cp node_modules/instant.page/instantpage.js                                       vendor/instant-page.js
  cp node_modules/@jaames/iro/dist/iro.js                                           vendor/iro.js
  cp node_modules/cronstrue/dist/cronstrue.js                                       vendor/cronstrue.js
  cp node_modules/prettier/standalone.js                                            vendor/prettier.js
  cp node_modules/prettier/plugins/babel.js                                         vendor/prettier-babel.js
  cp node_modules/prettier/plugins/estree.js                                        vendor/prettier-estree.js
  cp node_modules/prettier/plugins/postcss.js                                       vendor/prettier-postcss.js
  cp node_modules/prettier/plugins/html.js                                          vendor/prettier-html.js
  cp node_modules/terser/dist/bundle.min.js                                         vendor/terser.js
  cp node_modules/csso/dist/csso.js                                                 vendor/csso.js
  cp node_modules/html-minifier-terser/dist/htmlminifier.umd.bundle.min.js          vendor/html-minifier.js
  cp -r node_modules/uuid/dist/esm-browser                                          vendor/uuid
  cp node_modules/@huggingface/transformers/dist/ort-wasm-simd-threaded.jsep.mjs    vendor/
  cp node_modules/@huggingface/transformers/dist/ort-wasm-simd-threaded.jsep.wasm   vendor/

  bun build --target browser --format esm node_modules/@huggingface/transformers/dist/transformers.web.js --outfile vendor/transformers.js >/dev/null
}

serve() {
  waiter --dev
}

precache() {
  {
    find . -maxdepth 1 -name "*.html"
    find . -maxdepth 1 -name "*.css"
    find . -maxdepth 1 -name "*.json"
    find . -maxdepth 1 -name "*.js" ! -name "sw.js"
    find ./vendor -type f
  } | sort > .listing.tmp

  CACHE_HASH=$(xargs cat < .listing.tmp | openssl dgst -sha1 | awk '{print $NF}' | cut -c1-8)

  sed "s|^\./|/|; s|.*|  '&',|" .listing.tmp > .precache.tmp

  awk -v hash="tools-${CACHE_HASH}" '
    /^const CACHE_KEY = / { q=sprintf("%c", 39); print "const CACHE_KEY = " q hash q ";"; next }
    /^const PRECACHE = \[/ { print; in_block=1; while ((getline line < ".precache.tmp") > 0) print line; next }
    /^\];/ && in_block { in_block=0 }
    !in_block { print }
  ' sw.js > .sw.tmp && mv .sw.tmp sw.js

  rm .listing.tmp .precache.tmp
}

deploy() {
  lift deploy
}
